apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.metadata.name }}-sshkey"
  namespace: {{ include "hostedClusterNamespace" . | quote }}
data:
  id_rsa.pub: {{ .Values.sshKey | b64enc | quote }}
type: Opaque
---
{{- if hasKey .Values "additionalTrustBundle" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: trusted-ca
  namespace: {{ include "hostedClusterNamespace" . | quote }}
data:
  ca-bundle.crt: |
    {{- .Values.additionalTrustBundle |  nindent 4 }}
---
{{- end }}
apiVersion: hypershift.openshift.io/v1beta1
kind: HostedCluster
metadata:
  name: {{ .Values.metadata.name | quote }}
  namespace: {{ include "hostedClusterNamespace" . | quote }}
  annotations:
    helm.sh/hook-weight: "20"
{{- if hasKey .Values.hypershift "controlPlaneOperatorImage" }}
    hypershift.openshift.io/control-plane-operator-image: {{ .Values.hypershift.controlPlaneOperatorImage | quote }}
{{- end }}
    hypershift.openshift.io/certified-operators-catalog-image: registry.redhat.io/redhat/certified-operator-index@sha256:ec153792abd37e7524d076b02b1546160e240964c62b0e51d609acc8e61c66ba
    hypershift.openshift.io/community-operators-catalog-image: registry.redhat.io/redhat/community-operator-index@sha256:1d682bf744725289ad88e9ffd29ee36027639fba712d4968235eafb40dcd1b77
    hypershift.openshift.io/redhat-operators-catalog-image: registry.redhat.io/redhat/redhat-operator-index@sha256:ca4718088f5deaf96c37842805f921c3a1b3a45a6057df4313971e9f12ddec39
    hypershift.openshift.io/redhat-marketplace-catalog-image: registry.redhat.io/redhat/redhat-marketplace-index@sha256:2bd47016e0e36c58b5824c2c7f61ef44f7c53dd51feb0de388b5bc34e1f8b560
spec:
  release:
    image: {{ .Values.hypershift.clusterImageSet | quote }}
  platform:
    type: "Agent"
    agent:
      agentNamespace: {{ include "clusterNamespace" . }}
  dns:
    baseDomain: {{ .Values.baseDomain | quote }}
  networking:
    {{- omit .Values.networking "serviceNetwork" | toYaml | nindent 4 }}
{{- if hasKey .Values.networking "serviceNetwork" }}
    serviceNetwork:
  {{- range .Values.networking.serviceNetwork }}
      - cidr: {{ . | quote }}
  {{- end }}
{{- end }}
  pullSecret:
    name: {{ .Values.metadata.name }}-pull-secret
  sshKey:
    name: "{{ .Values.metadata.name }}-sshkey"
{{- if hasKey .Values "fips" }}
  fips: {{ .Values.fips }}
{{- end }}
{{- if hasKey .Values "imageContentSources" }}
  imageContentSources:
    {{- .Values.imageContentSources | toYaml | nindent 4 }}
{{- end }}
{{- if hasKey .Values "additionalTrustBundle" }}
  additionalTrustBundle:
    name: trusted-ca
{{- end }}
{{- if hasKey .Values.hypershift "clusterConfiguration" }}
  configuration:
    {{- .Values.hypershift.clusterConfiguration | toYaml | nindent 4 }}
{{- end }}
  services:
    - service: APIServer
      servicePublishingStrategy:
        type: LoadBalancer
        loadBalancer:
          hostname: "api.{{ .Values.metadata.name }}.{{ .Values.baseDomain }}"
    - service: OAuthServer
      servicePublishingStrategy:
        type: Route
    - service: OIDC
      servicePublishingStrategy:
        type: Route
    - service: Konnectivity
      servicePublishingStrategy:
        type: Route
    - service: Ignition
      servicePublishingStrategy:
        type: Route
    - service: OVNSbDb
      servicePublishingStrategy:
        type: Route
{{- if hasKey .Values.hypershift "olmCatalogPlacement" }}
  olmCatalogPlacement: {{ .Values.hypershift.olmCatalogPlacement | quote }}
{{- end }}
