apiVersion: v1
kind: Secret
data:
  .dockerconfigjson: {{ .Values.pullSecret | b64enc | quote }}
metadata:
  name: {{ .Values.metadata.name }}-pull-secret
  namespace: {{ include "hostedClusterNamespace" . | quote }}
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
data:
  .dockerconfigjson: {{ .Values.pullSecret | b64enc | quote }}
metadata:
  name: {{ .Values.metadata.name }}-pull-secret
  namespace: {{ include "clusterNamespace" . | quote }}
type: kubernetes.io/dockerconfigjson
---
